-- EKPOChangeJoyline

DROP TABLE IF EXISTS "EKPOChangeJoyline";

CREATE TABLE "EKPOChangeJoyline" AS
SELECT DISTINCT 
    "CDPOS".*
FROM 
    "CDPOS"
INNER JOIN 
    "EKPO"
    ON "CDPOS"."TABKEY" = "EKPO"."_CASE_KEY"
WHERE 
    "CDPOS"."TABNAME" = 'EKPO';
