DROP TABLE IF EXISTS "EKKOChangeJoyline";

CREATE TABLE "EKKOChangeJoyline" AS
SELECT DISTINCT 
    "CDPOS".*
FROM 
    "CDPOS"
INNER JOIN 
    "EKKO"
    ON "CDPOS"."OBJECTID" = "EKKO"."EBELN"
WHERE 
    "CDPOS"."TABNAME" = 'EKKO';
