DROP TABLE IF EXISTS "EKKOChangeJoyline";

CREATE TABLE "EKKOChangeJoyline" AS
SELECT DISTINCT 
    "CDHDR".*
FROM 
    "CDHDR"
INNER JOIN 
    "EKKO"
    ON "CDHDR"."OBJECTID" = "EKKO"."EBELN"
WHERE 
    "CDHDR"."TABNAME" = 'EKKO';


SELECT * FROM EKKOChangeJoyline;
SELECT * FROM EKPOChangeJoyline;
