SELECT
	"_CASE_KEY" AS "ID",
	"EBELP" AS "EBELP",
	"MANDT" AS "MANDT",
	"AEDAT" AS "AEDAT",
	"BUKRS" AS "BUKRS",
	"KTPNR" AS "KTPNR",
	"BANFN" AS "BANFN",
	"BNFPO" AS "BNFPO",
	"NETWR" AS "NETWR",
	"NETWR_CONVERTED" AS "NetwrConverted",
	"NETPR" AS "NETPR",
	"NETPR_CONVERTED" AS "NetprConverted",
	"LOEKZ" AS "LOEKZ",
	"MATKL" AS "MATKL",
	"MATNR" AS "MATNR",
	"MENGE" AS "MENGE",
	"MEINS" AS "MEINS",
	"BPUMZ" AS "BPUMZ",
	"BPUMN" AS "BPUMN",
	"MTART" AS "MTART",
    EKPO."EBELN" AS "EKKO",
    "EKKO"."BSTYP" AS newAttribute
FROM "EKPO" as "EKPO" INNER JOIN 
(SELECT EBELN, BSTYP FROM "EKKO") AS EKKO
ON EKPO.EBELN = EKKO.EBELN
