   ******************************   POPULATING THE OBJECT ATTRIBUTES ********************
SELECT
	"_CASE_KEY" AS "ID",
	"EBELP" AS "EBELP",
	"MANDT" AS "MANDT",
	"AEDAT" AS "AEDAT",
	"BUKRS" AS "BUKRS",
	"KTPNR" AS "KTPNR",
	"BANFN" AS "BANFN",
	"BNFPO" AS "BNFPO",
	"NETWR" AS "NETWR",
	"NETWR_CONVERTED" AS "NetwrConverted",
	"NETPR" AS "NETPR",
	"NETPR_CONVERTED" AS "NetprConverted",
	"LOEKZ" AS "LOEKZ",
	"MATKL" AS "MATKL",
	"MATNR" AS "MATNR",
	"MENGE" AS "MENGE",
	"MEINS" AS "MEINS",
	"BPUMZ" AS "BPUMZ",
	"BPUMN" AS "BPUMN",
	"MTART" AS "MTART",
    EKPO."EBELN" AS "EKKO",
    "EKKO"."BSTYP" AS newAttribute
FROM "EKPO" as "EKPO" INNER JOIN 
(SELECT EBELN, BSTYP FROM "EKKO") AS EKKO
ON EKPO.EBELN = EKKO.EBELN

or 

WITH LARA AS
(SELECT BSTYP, EBELN FROM EKKO)

SELECT
	"_CASE_KEY" AS "ID",
    "EBELP" AS "EBELP",
	"MANDT" AS "MANDT",
	"AEDAT" AS "AEDAT",
    "BUKRS" AS "BUKRS",
	"KTPNR" AS "KTPNR",
	"BANFN" AS "BANFN",
	"BNFPO" AS "BNFPO",
	"NETWR" AS "NETWR",
	"NETWR_CONVERTED" AS "NetwrConverted",
	"NETPR" AS "NETPR",
	"NETPR_CONVERTED" AS "NetprConverted",
	"LOEKZ" AS "LOEKZ",
	"MATKL" AS "MATKL",
	"MATNR" AS "MATNR",
	"MENGE" AS "MENGE",
	"MEINS" AS "MEINS",
	"BPUMZ" AS "BPUMZ",
	"BPUMN" AS "BPUMN",
	"MTART" AS "MTART",
	EKPO."EBELN" AS "EKKO",
    "EKKO"."BSTYP" as newAttribute
FROM "EKPO"
INNER JOIN 
    LARA AS EKKO ON 
    EKPO.EBELN = EKKO.EBELN


 ***************************    POPULATING OBJECT CHANGES  EKPO *******************************


SELECT
	'Update_' || "CDPOS"."TABKEY" AS "ID",
	"CDPOS"."TABKEY" AS "ObjectID", -- FROM EKPO
	"CDPOS"."EVENTTIME" AS "Time", -- FROM CDHDR
	"CDPOS"."FNAME" AS "Attribute",
	"CDPOS"."VALUE_OLD" AS "OldValue",
	"CDPOS"."VALUE_NEW" AS "NewValue",
	"CDPOS"."USERNAME" AS "ChangedBy",
	NULL AS "OperationType",
	NULL AS "OperationID",
	NULL AS "ExecutionType"
FROM CDPOS
JOIN EKPO  
ON EKPO.MANDT || EKPO.EBELN || EKPO.EBELP = CDPOS.TABKEY
WHERE CDPOS.TABNAME = 'EKPO'
AND "CDPOS"."CHNGIND" = 'U'
