******************************   POPULATING THE OBJECT ATTRIBUTES ****************************

SELECT
	"EBELN" AS "ID",
	"MANDT" AS "MANDT",
	"BUKRS" AS "BUKRS",
	"SUBMITDATE" AS "SUBMITDATE",
	"ORDEREDDATE" AS "ORDEREDDATE",
	"CREATEDATE" AS "CREATEDATE",
	"BSTYP" AS "BSTYP",
	"BSART" AS "BSART",
	"AEDAT" AS "AEDAT",
	"ERNAM" AS "ERNAM",
	"EKORG" AS "EKORG",
	"EKORG_TEXT" AS "EkorgText",
	"WAERS" AS "WAERS",
	"WKURS" AS "WKURS",
	"ZTERM" AS "ZTERM",
	"ZBD1T" AS "ZBD1T",
	"ZBD2T" AS "ZBD2T",
	"ZBD3T" AS "ZBD3T",
	"EKGRP" AS "EKGRP",
	"BEDAT" AS "BEDAT",
	"PROCSTAT" AS "PROCSTAT",
	"FRGZU" AS "FRGZU",
	"FRGKE" AS "FRGKE",
	"FRGGR" AS "FRGGR"
FROM "EKKO"

******************************   POPULATING THE OBJECT CHANGES ****************************	

SELECT
	'Update_' || "CDPOS"."TABKEY" AS "ID",
	"CDPOS"."TABKEY" AS "ObjectID",           -- FROM EKPO COZ THEY ARE SAME
	"CDPOS"."EVENTTIME" AS "Time",            -- FROM CDHDR COZ OF SAME VALUE
	"CDPOS"."FNAME" AS "Attribute",
	"CDPOS"."VALUE_OLD" AS "OldValue",
	"CDPOS"."VALUE_NEW" AS "NewValue",
	"CDPOS"."USERNAME" AS "ChangedBy",
	"CDPOS"."CHNGIND" AS "OperationType",
	NULL AS "OperationID",
	NULL AS "ExecutionType"
FROM CDPOS
JOIN EKKO  
ON EKKO.MANDT || EKKO.EBELN  = CDPOS.MANDANT || CDPOS.ObjectID
WHERE CDPOS.TABNAME = 'EKPO'
AND CDPOS.CHNGIND IN ('U', 'I', 'D')
