DROP TABLE IF EXISTS _CEL_P2P_EKPO_ACTIVITIES;

CREATE TABLE _CEL_P2P_EKPO_ACTIVITIES (
    _CASE_KEY VARCHAR(50)
    ,ACTIVITY_EN VARCHAR(200)
    ,_ACTIVITY_KEY VARCHAR(50)
    ,MANDT VARCHAR(3)
    ,EBELN VARCHAR(10)
    ,EBELP VARCHAR(5)
    ,ACTIVITY_DE VARCHAR (300)
    ,EVENTTIME DATETIME
    ,_SORTING INT
    ,USER_NAME VARCHAR(100)
    ,USER_TYPE VARCHAR(10)
    ,CHANGED_TABLE VARCHAR(20)
    ,CHANGED_TABLE_TEXT_DE VARCHAR(200)
    ,CHANGED_TABLE_TEXT_EN VARCHAR(200)
    ,CHANGED_FIELD VARCHAR(20)
    ,CHANGED_FIELD_TEXT_DE VARCHAR(200)
    ,CHANGED_FIELD_TEXT_EN VARCHAR(200)
    ,CHANGED_FROM VARCHAR (50)
    ,CHANGED_TO VARCHAR(50)
    ,CHANGED_FROM_FLOAT FLOAT
    ,CHANGED_TO_FLOAT FLOAT
    ,CHANGE_NUMBER VARCHAR(50)
    ,TRANSACTION_CODE VARCHAR(20)
--    ,_CELONIS_CHANGE_DATE DATETIME

)
ORDER BY 	
  _CASE_KEY 
 	,ACTIVITY_EN 
  ,_ACTIVITY_KEY
;

select * from _CEL_P2P_EKPO_ACTIVITIES;
