-- SELECT * FROM "_CEL_P2P_EKPO_ACTIVITIES";
-- DROP TABLE IF EXISTS _CEL_P2P_EKPO_ACTIVITIES_1;

-- CREATE TABLE _CEL_P2P_EKPO_ACTIVITIES_1 AS
-- (SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES WHERE ACTIVITY_EN = 'Create Purchase Requisition Item' LIMIT 5)
-- UNION ALL 
-- (SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES WHERE ACTIVITY_EN = 'Create Purchase Order Item' LIMIT 5)


-- SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES_1;
-- SELECT DISTINCT ACTIVITY_EN FROM _CEL_P2P_EKPO_ACTIVITIES_1;
-- SELECT DISTINCT ACTIVITY_EN FROM _CEL_P2P_EKPO_ACTIVITIES;


DROP TABLE IF EXISTS _CEL_P2P_EKPO_ACTIVITIES_1;
CREATE TABLE _CEL_P2P_EKPO_ACTIVITIES_1 AS
(
    SELECT * FROM (
        SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES 
        WHERE ACTIVITY_EN = 'Create Purchase Requisition Item' 
        LIMIT 5
    ) AS req
    UNION ALL
    SELECT * FROM (
        SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES 
        WHERE ACTIVITY_EN = 'Create Purchase Order Item' 
        LIMIT 5
    ) AS po
);
SELECT DISTINCT ACTIVITY_EN FROM _CEL_P2P_EKPO_ACTIVITIES_1;
