SELECT * FROM "_CEL_P2P_EKPO_ACTIVITIES";

CREATE TABLE _CEL_P2P_EKPO_ACTIVITIES_1 AS 
(SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES WHERE ACTIVITY_EN = 'Create Purchase Requisition Item' LIMIT 5)
UNION ALL 
(SELECT * FROM _CEL_P2P_EKPO_ACTIVITIES WHERE ACTIVITY_EN = 'Create Purchase Order Item' LIMIT 5)

SELECT * FROM "_CEL_P2P_EKPO_ACTIVITIES_1";
SELECT DISTINCT ACTIVITY_EN FROM _CEL_P2P_EKPO_ACTIVITIES_1;
SELECT DISTINCT ACTIVITY_EN FROM _CEL_P2P_EKPO_ACTIVITIES;
