DROP TABLE IF EXISTS BKPF_RSEG;

CREATE TABLE BKPF_RSEG AS
SELECT
  -- Celonis-style CASE KEY
  RSEG.MANDT || RSEG.BUKRS_EKPO || RSEG.BELNR || RSEG.GJAHR || RSEG.BUZEI AS _CASE_KEY,

  -- All RSEG fields
  RSEG.MANDT,
  RSEG.BUKRS_EKPO AS BUKRS,
  RSEG.BELNR,
  RSEG.GJAHR,
  RSEG.BUZEI,
  RSEG.LFBNR,
  RSEG.LFGJA,
  RSEG.LFPOS,
  RSEG.SHKZG AS RSEG_SHKZG,
  RSEG.SPGRM,
  RSEG.WRBTR,
  RSEG.MENGE,
  RSEG.EBELN_EKPO,
  RSEG.EBELP_EKPO,
  -- RSEG.BUKRS_EKPO,
  RSEG.NETPR_EKPO,
  RSEG.NETWR_EKPO,
  RSEG.MATNR_EKPO,
  RSEG.WERKS_EKPO,
  RSEG.ZTERM_EKKO,
  RSEG.WAERS_EKKO,
  RSEG.LIFNR_EKKO,
  RSEG.BEDAT_EKKO,
  RSEG._CASE_KEY AS RSEG_CASE_KEY,
  RSEG._CELONIS_CHANGE_DATE AS RSEG_CHANGE_DATE,

  -- All BKPF fields 
  BKPF.BUKRS AS BKPF_BUKRS,
  BKPF.BLART,
  BKPF.BLDAT,
  BKPF.CPUDT,
  BKPF.CPUTM,
  BKPF.BUDAT,
  BKPF.MONAT,
  BKPF.AEDAT,
  BKPF.USNAM,
  BKPF.WAERS AS BKPF_WAERS,
  BKPF.KURSF,
  BKPF.GLVOR,
  BKPF.AWTYP,
  BKPF.AWKEY,
  BKPF.HWAER,
  BKPF.HWAE2,
  BKPF.KURS2,
  BKPF.BASW2,
  BKPF.UMRD2,
  BKPF.CURT2,
  BKPF.KUTY2,
  BKPF.XSNET,
  BKPF.XSTOV,
  BKPF.XMWST,
  BKPF.DOCCAT,
  BKPF.KURST,
  BKPF._CELONIS_CHANGE_DATE AS BKPF_CHANGE_DATE

FROM RSEG
LEFT JOIN BKPF ON 1=1
--  AND RSEG.BELNR = BKPF.BELNR
 AND RSEG.BUKRS_EKPO = BKPF.BUKRS
 AND RSEG.GJAHR = BKPF.GJAHR
 AND RSEG.MANDT = BKPF.MANDT;


select * from BKPF_RSEG;
